apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: ums-cd
spec:
  replicas: 2
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: francisnwachukwu100/smartopsapp:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: front-end
  namespace: ums-cd
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: front-end
